### ISSUE TITLE
Not pip installable from github

### ISSUE THREAD

**Issue by frankier** [dmlc/decord#117]
Pip supports installing packages directly from GitHub, which can be convenient when needing a fix from master or making a temporary fork. However, this requires that setup.py is at the project root.

```
$ pip install --user https://github.com/dmlc/decord
Collecting git+https://github.com/dmlc/decord.git
  Cloning https://github.com/dmlc/decord.git to /tmp/pip-req-build-w5ihosab
  Running command git clone -q https://github.com/dmlc/decord.git /tmp/pip-req-build-w5ihosab
  Running command git submodule update --init --recursive -q
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-w5ihosab/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-w5ihosab/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-j38etdgp
         cwd: /tmp/pip-req-build-w5ihosab/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.8/tokenize.py", line 392, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-w5ihosab/setup.py'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by zhreshold** [comment]
This is not a pure python package,  c++ projects needs to be built with dependencies like ffmpeg. Is not trivial to support pip installation via git.
