### ISSUE TITLE
GPU Decord and Tensorflow bridge

### ISSUE THREAD

**Issue by mwoodson1** [dmlc/decord#132]
I am working with GPU accelerated Decord and am running into an issue using Decord with Tensorflow. In particular, I am running into the error below

```
Traceback (most recent call last):
  File "src/dataloader.py", line 373, in <module>
    frames = vr[0:10]
  File "/root/.local/lib/python3.6/site-packages/decord-0.4.2-py3.6-linux-x86_64.egg/decord/video_reader.py", line 96, in __getitem__
    return self.get_batch(range(*idx.indices(len(self))))
  File "/root/.local/lib/python3.6/site-packages/decord-0.4.2-py3.6-linux-x86_64.egg/decord/video_reader.py", line 173, in get_batch
    return bridge_out(arr)
  File "/root/.local/lib/python3.6/site-packages/decord-0.4.2-py3.6-linux-x86_64.egg/decord/bridge/__init__.py", line 40, in bridge_out
    return _BRIDGE_TYPES[_CURRENT_BRIDGE.type][0](native_arr)
  File "/root/.local/lib/python3.6/site-packages/decord-0.4.2-py3.6-linux-x86_64.egg/decord/bridge/tf.py", line 21, in to_tensorflow
    return tfdl.from_dlpack(decord_arr.to_dlpack())
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/dlpack/dlpack.py", line 66, in from_dlpack
    return pywrap_tfe.TFE_FromDlpackCapsule(dlcapsule, context.context()._handle)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/context.py", line 752, in _handle
    raise AssertionError("Context must be initialized first.")
AssertionError: Context must be initialized first.
```

The code that produces this error is:

```
vr = VideoReader(video_path, ctx=gpu(0))
decord.bridge.set_bridge('tensorflow')
frames = vr[0:10]
print(frames.shape)
```

I can tell it is the Tensorflow bridge causing issues as if I remove the second line everything works fine and frames are correctly extracted. Also if I switch the context to cpu then the code works as well no problem. Would appreciate any help here.

This is happening with Tensorflow v2.3.0, Python 3.6.9, and CUDA 10.1.

**Comment by seuyou** [comment]
the same problem

**Comment by zhreshold** [comment]
suspect that there must be at least a single call to initialize the corresponding gpu in tensorflow, @mwoodson1 would you mind try if executing anything on gpu(0) before running the code snippet you provided will solve this issue?

**Comment by mwoodson1** [comment]
All of the GPU's on my machine are unoccupied when I run the code above.

**Comment by zhreshold** [comment]
@mwoodson1 yes, that's probably the reason, tensorflow needs to initiate cuda context first in their dlpack bridge

File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/dlpack/dlpack.py", line 66, in from_dlpack
    return pywrap_tfe.TFE_FromDlpackCapsule(dlcapsule, context.context()._handle)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/context.py", line 752, in _handle
    raise AssertionError("Context must be initialized first.")

The current workaround is to create a gpu variable on gpu first.
