### ISSUE TITLE
error after fixed #138

### ISSUE THREAD

**Issue by TIMETOTIAO** [dmlc/decord#143]
Really thanks for updating the code. But I still meet error after getting the most recent version. And where should I export the DECORD_EOF_RETRY_MAX=20480 to try? Thanks

python3 experiment.py --data_config config/indoor_short.data --k 20 --conf 0.1 --score_func count
Namespace(budget=1000, conf='0.1', data_config='config/indoor_short.data', gpu=0, k='20', log='log/log_*', order=None, record='result/record', score_func='count', skip_infer=False, skip_split=False, skip_topk=False, skip_train=False, window='1')
Namespace(data_config='config/indoor_short.data', equal_interval=False, gpu=0, random_seed=0, score_func='count')
[EXP]split_time: 192.74919438362122
epoch 1/10: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 9/9 [01:34<00:00, 10.53s/it]
epoch 2/10: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:01<00:00,  4.74it/s]
epoch 3/10: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:01<00:00,  4.73it/s]
epoch 4/10: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:01<00:00,  4.74it/s]
epoch 5/10: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:01<00:00,  4.73it/s]
epoch 6/10: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:01<00:00,  4.72it/s]
epoch 7/10: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:01<00:00,  4.73it/s]
epoch 8/10: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:01<00:00,  4.72it/s]
epoch 9/10: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:01<00:00,  4.70it/s]
epoch 10/10: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:01<00:00,  4.71it/s]
Detecting objects:  64%|██████████████████████████████████████████████████████████████████████████████████████████████▍                                                     | 30/47 [05:53<03:18, 11.67s/it]Exception in thread Thread-3:
Traceback (most recent call last):
  File "/home/wlai/.pyenv/versions/3.8.7/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/wlai/.pyenv/versions/3.8.7/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/wlai/wlai_backup/video-analytic/utils/datasets.py", line 350, in loader_thread
    imgs = video_reader.get_batch(batch_idx)
  File "/home/wlai/wlai_backup/video-analytic/utils/video_reader.py", line 57, in get_batch
    return self._vr.get_batch(batch).permute(0, 3, 1, 2).contiguous().float().div(255)
  File "/home/wlai/.local/lib/python3.8/site-packages/decord-0.5.2-py3.8-linux-x86_64.egg/decord/video_reader.py", line 175, in get_batch
    arr = _CAPI_VideoReaderGetBatch(self._handle, indices)
  File "/home/wlai/.local/lib/python3.8/site-packages/decord-0.5.2-py3.8-linux-x86_64.egg/decord/_ffi/_ctypes/function.py", line 173, in __call__
    check_call(_LIB.DECORDFuncCall(
  File "/home/wlai/.local/lib/python3.8/site-packages/decord-0.5.2-py3.8-linux-x86_64.egg/decord/_ffi/base.py", line 78, in check_call
    raise DECORDError(err_str)
decord._ffi.base.DECORDError: [14:48:04] /home/wlai/decord/src/video/video_reader.cc:444: [/home/wlai/wlai_backup/resized_video/indoor_short.mp4]Unable to handle EOF because it takes too long to retrieve last few frames and `DECORD_EOF_RETRY_MAX=10240`. You may override the limit by `export DECORD_EOF_RETRY_MAX=20480` for example to allow more EOF retry attempts, exit...

**Comment by TIMETOTIAO** [comment]
After changing export DECORD_EOF_RETRY_MAX=20480, still error. How can I fix this problem by modifying my mp4 file like fps or timestamp? Thanks a lot

**Comment by TIMETOTIAO** [comment]
> Can you post your gpu model and cuda version? You may continue using a much larger RETRY threshold, like 100 time larger DECORD_EOF_RETRY_MAX to get around.

![image](https://user-images.githubusercontent.com/46701471/111054358-0c8e7680-84a7-11eb-80c2-556e472a6040.png)
Here is the information.

**Comment by DmitryUlyanov** [comment]
@zhreshold I also have this error turning up at random. And sometimes there is no error, but one of the frames in the end of the sequence is completely black. My system is CUDA 11.1, tested on 3090 and 1080ti.
