### ISSUE TITLE
VideoReader Error

### ISSUE THREAD

**Issue by meocong** [dmlc/decord#146]
Thanks for the great work, but I have one problem when read some videos like this one: [https://drive.google.com/file/d/13vkGsQQWQKbvLgi23CuS4WQLWI0LxYxJ/view?usp=sharing](LINK)

I installed decord from Pypi, can you check it for me? @zhreshold. Thank you a lot!

**Comment by meocong** [comment]
@yinweisu Can you take a time to check this video, thank you a lot!

**Comment by zhuipiaochen** [comment]
> @yinweisu Can you take a time to check this video, thank you a lot!

Have you fixed the problem yet? I have the same problem.

Traceback (most recent call last):
  File "mike.py", line 34, in <module>
    vr = VideoReader(f, ctx=cpu(0))
  File "/root/.local/lib/python3.7/site-packages/decord-0.6.0-py3.7-linux-x86_64.egg/decord/video_reader.py", line 52, in __init__
    ba, ctx.device_type, ctx.device_id, width, height, num_threads, 2, fault_tol)
  File "/root/.local/lib/python3.7/site-packages/decord-0.6.0-py3.7-linux-x86_64.egg/decord/_ffi/_ctypes/function.py", line 175, in __call__
    ctypes.byref(ret_val), ctypes.byref(ret_tcode)))
  File "/root/.local/lib/python3.7/site-packages/decord-0.6.0-py3.7-linux-x86_64.egg/decord/_ffi/base.py", line 78, in check_call
    raise DECORDError(err_str)
decord._ffi.base.DECORDError: [22:56:36] /workspace/3rd/decord/src/video/video_reader.cc:270: [BytesIO] Failed to measure duration/frame-count due to broken metadata.
