### ISSUE TITLE
CUDA: initialization error

### ISSUE THREAD

**Issue by psandev** [dmlc/decord#159]
Hi,
I compiled the latest repo: 0.5.3,  and received the error below. This specific file was read without an issue in a cpu context. 
[cuda_stream.zip](https://github.com/dmlc/decord/files/6634102/cuda_stream.zip)
Attached is the file in which the error occurs,

Traceback (most recent call last):
  File "/home/peter/virtualenvs/dl_387/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3441, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-1-c2f1d01cb490>", line 1, in <module>
    vr = VideoReader(fname, num_threads=3, ctx=gpu())
  File "/home/peter/virtualenvs/dl_387/lib/python3.8/site-packages/decord-0.5.3-py3.8-linux-x86_64.egg/decord/video_reader.py", line 54, in __init__
    self._handle = _CAPI_VideoReaderGetVideoReader(
  File "/home/peter/virtualenvs/dl_387/lib/python3.8/site-packages/decord-0.5.3-py3.8-linux-x86_64.egg/decord/_ffi/_ctypes/function.py", line 173, in __call__
    check_call(_LIB.DECORDFuncCall(
  File "/home/peter/virtualenvs/dl_387/lib/python3.8/site-packages/decord-0.5.3-py3.8-linux-x86_64.egg/decord/_ffi/base.py", line 78, in check_call
    raise DECORDError(err_str)
decord._ffi.base.DECORDError: [22:45:27] /home/peter/Downloads/decord/src/video/nvcodec/cuda_stream.cc:20: Check failed: e == cudaSuccess || e == cudaErrorCudartUnloading CUDA: initialization error at line: 20 in file: /home/peter/Downloads/decord/src/video/nvcodec/cuda_stream.cc

CUDA Toolkit 11.1
NVidia driver : 465.37
Ubuntu 18.04
python 3.8.5

**Comment by zhreshold** [comment]
due to cuda restriction, two processes can't share the same cuda context so that might be the problem, if you are using multiprocessing or similar stuff, it will trigger this error

**Comment by psandev** [comment]
Thank you for this explanation. I am not using multiprocessing explicitly,
but could be that the Dali pipeline uses multiple cuda streams by default?
And this exception enforces a single stream? Could this be the performance
hit it warns about?

**Comment by arthurmjt** [comment]
@psandev Have you solved the problem?
