### ISSUE TITLE
Failed to measure duration/frame-count due to broken metadata.

### ISSUE THREAD

**Issue by Iamlearn** [dmlc/decord#224]
I have a video that opencv can read, but the record will report an error, the code is as follows：
`
import time
from decord import VideoReader, cpu
path = r'X:\007\SaveImg\Cuda.mp4'
start = time.time()
vr = VideoReader(path, ctx=cpu(0))
startP = 0
imgs2 = vr.get_batch(range(startP, startP + 512)).asnumpy()
print(imgs2.shape, time.time() - start)
`
Error：
decord._ffi.base.DECORDError: [20:11:48] D:\a\decord\decord\src\video\video_reader.cc:270: [X:\007\SaveImg\Cuda.mp4] Failed to measure duration/frame-count due to broken metadata.
Process finished with exit code 1
The video is in the attachment,And Decord version==0.6.0

https://user-images.githubusercontent.com/46410827/182611605-4d9e3e6f-dd46-4d00-8938-e6f813e29476.mp4

**Comment by Iamlearn** [comment]
The format of the code just pasted is wrong, re-paste it as follows

import time
from decord import VideoReader, cpu
path = r'X:\007\SaveImg\Cuda.mp4'
start = time.time()
vr = VideoReader(path, ctx=cpu(0))
startP = 0
imgs2 = vr.get_batch(range(startP, startP + 512)).asnumpy()
print(imgs2.shape, time.time() - start)

**Comment by CDUAP** [comment]
Traceback (most recent call last):
  File "C:\documents\workspeace\pycharm\mmaction2\demo\demo_ldb\decord_read_error.py", line 100, in <module>
    decord_write_error()
  File "C:\documents\workspeace\pycharm\mmaction2\demo\demo_ldb\decord_read_error.py", line 92, in decord_write_error
    vr = VideoReader(path, ctx=cpu(0))
  File "C:\documents\installed\Miniconda3\envs\openmmlab\lib\site-packages\decord\video_reader.py", line 54, in __init__
    self._handle = _CAPI_VideoReaderGetVideoReader(
  File "C:\documents\installed\Miniconda3\envs\openmmlab\lib\site-packages\decord\_ffi\_ctypes\function.py", line 173, in __call__
    check_call(_LIB.DECORDFuncCall(
  File "C:\documents\installed\Miniconda3\envs\openmmlab\lib\site-packages\decord\_ffi\base.py", line 78, in check_call
    raise DECORDError(err_str)
decord._ffi.base.DECORDError: [00:06:52] D:\a\decord\decord\src\video\video_reader.cc:270: [C:\documents\workspeace\pycharm\mmaction2\demo\clientdata_org\\5.mp4] Failed to measure duration/frame-count due to broken metadata.
