### ISSUE TITLE
cannot read frames. error message is corrupted framesand

### ISSUE THREAD

**Issue by JamesSand** [dmlc/decord#248]
the whole errors are the followings

[h264 @ 0x180fd80] no frame!
video frames: 186146
Traceback (most recent call last):
  File "video_reader.py", line 23, in <module>
    height, width, _ = vr[1].shape
  File "/zhangpai21/envs/detection/lib/python3.8/site-packages/decord/video_reader.py", line 105, in __getitem__
    return self.next()
  File "/zhangpai21/envs/detection/lib/python3.8/site-packages/decord/video_reader.py", line 117, in next
    arr = _CAPI_VideoReaderNextFrame(self._handle)
  File "/zhangpai21/envs/detection/lib/python3.8/site-packages/decord/_ffi/_ctypes/function.py", line 173, in __call__
    check_call(_LIB.DECORDFuncCall(
  File "/zhangpai21/envs/detection/lib/python3.8/site-packages/decord/_ffi/base.py", line 78, in check_call
    raise DECORDError(err_str)
decord._ffi.base.DECORDError: [15:04:47] /github/workspace/src/video/video_reader.cc:430: [拼多多2-动画电影1000部/100部英语电影（原音双语大字幕带台词）/30部儿童电影（无台词）/Z.蜘蛛侠：英雄远征.mp4]Unable to handle EOF because the video might have corrupted framesand `DECORD_REWIND_RETRY_MAX=16`. You may override the limit by `export DECORD_REWIND_RETRY_MAX=32` for example to allow more auto-substituded frames, exit...

I have tried export DECORD_REWIND_RETRY_MAX in python, using following code 

os.environ['DECORD_EOF_RETRY_MAX'] = "20480"

but it still don't work....
Please help me for that. Thanks a  lot

**Comment by simonnxren** [comment]
have you fixed the error?
