### ISSUE TITLE
Pyinstaller issues

### ISSUE THREAD

**Issue by NeighborhoodCoding** [dmlc/decord#253]
I build my exe with 
`pyinstaller a.py`

but a.exe has some issue when I run the files.
here is log.
```
Traceback (most recent call last):
  File "a.py", line 38, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "vqml_srv.py", line 13, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "vqml.py", line 45, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "decord\__init__.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "decord\_ffi\runtime_ctypes.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "decord\_ffi\base.py", line 47, in <module>
  File "decord\_ffi\base.py", line 37, in _load_lib
  File "decord\_ffi\libinfo.py", line 80, in find_lib_path
RuntimeError: Cannot find the files.
List of candidates:
D:\a\a\dist\b\decord\libdecord.dll
D:\a\a\dist\build\libdecord.dll
D:\a\a\dist\build\Release\libdecord.dll
D:\a\a\dist\lib\libdecord.dll
D:\a\a\libdecord.dll
D:\a\a\dist\vqml\decord\decord.dll
D:\a\a\dist\build\decord.dll
D:\a\a\dist\build\Release\decord.dll
D:\a\a\dist\lib\decord.dll
D:\a\a\decord.dll
[12392] Failed to execute script 'a' due to unhandled exception!
```

I found some error are quite frequently happen in pyinstaller.
It is the reason that the lib is built on C++?
How Can I get exe with pyinstaller that using decord?

Thx.

**Comment by petered** [comment]
I got this same error on MacOS.

Not sure exactly what the root cause is, or what would need to be fixed in decord, but I did find a way to "fix" the pyinstaller build.

Note - I'm using another fork of decord (which supports Mac M1: https://pypi.org/project/eva-decord/), but I suspect that makes no difference here.

**Problem 1:**
If I run the built app (`dist/MyApp.app`), I get 

```
  ...
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "decord/_ffi/base.py", line 47, in <module>
  File "decord/_ffi/base.py", line 37, in _load_lib
  File "decord/_ffi/libinfo.py", line 83, in find_lib_path
RuntimeError: Cannot find the files.
List of candidates:
/Users/peter/projects/my_app/dist/MyApp.app/Contents/MacOS/decord/libdecord.dylib
/Users/peter/projects/my_app/dist/MyApp.app/Contents/MacOS/libdecord.dylib
... a bunch of other locations.  
```
I solved that by just manually copying `libdecord.dylib` from my conda installation into the built app:

```
cp ~/appcode/miniforge3/envs/myenv/lib/python3.10/site-packages/decord/libdecord.dylib dist/MyApp.app/Contents/MacOS/
```

Then if I run again I'll get...

**Problem 2:**
 ... another error about not finding `.dylib` files like `libavformat.59.27.100.dylib`.

```
Traceback (most recent call last):
  File "PyInstaller/loader/pyimod03_ctypes.py", line 53, in __init__
  File "ctypes/__init__.py", line 374, in __init__
OSError: dlopen(/Users/peter/projects/my_app/dist/MyApp.app/Contents/MacOS/libdecord.dylib, 0x000A): Library not loaded: @loader_path/.dylibs/libavformat.59.27.100.dylib
  Referenced from: <B085CA25-DDBA-3259-9D4B-B8FE1B87D829> /Users/peter/projects/my_app/dist/MyApp.app/Contents/MacOS/libdecord.dylib
  Reason: tried: '/Users/peter/projects/my_app/dist/MyApp.app/Contents/MacOS/.dylibs/libavformat.59.27.100.dylib' (no such file), ...
```
It seems to be looking for them in the `.dylibs` subfolder, which does not exist.  The dylib files to exist, just outside of that subfolder, so I solved it by making a `.dylibs` which is a relative link to its own parent directory:

```
ln -s . dist/EagleEyesScan.app/Contents/MacOS/.dylibs
```

**Automating**
To automate this, I've added the following to my build script: 

```
DECORD_PATH=$(python -c "import decord, os; print(os.path.abspath(os.path.join(decord.__file__, '..', 'libdecord.dylib')))")
cp "$DECORD_PATH" dist/"$APP_NAME".app/Contents/MacOS/libdecord.dylib
ln -s . dist/"$APP_NAME".app/Contents/MacOS/.dylibs
```

**Comment by petered** [comment]
And on windows, you can fix the problem by copying all the *.dll files from wherever your decord installation is to `dist/AppName/decord`.  I do this by running the following powershell script right after the pyinstaller build: 

```
$DECORD_PATH = python -c "import decord, os; print(os.path.abspath(os.path.join(decord.__file__, '..', 'decord.dll')))"
$destDir = "dist/$APP_NAME/decord"
if (!(Test-Path -Path $destDir)) { New-Item -ItemType Directory -Force -Path $destDir }
$sourceDir = Split-Path $DECORD_PATH
Copy-Item -Path "$sourceDir/*.dll" -Destination $destDir
```

**Comment by petered** [comment]
Actually even after those fixes, some machine (e.g. Mac Air M1 running older 11.2 OS) are continuing to have errors on `import decord` 

So I've just made a plug-in replacement using pyav, that will fall back on pyav if the decord import fails.:

https://github.com/petered/artemis/blob/f8ea9619b320013003fb7869b25aa305bbb6cba1/artemis/image_processing/decorders.py 

See test: 

https://github.com/petered/artemis/blob/f8ea9619b320013003fb7869b25aa305bbb6cba1/artemis/image_processing/test_decorders.py

Can be gotten with 

```
pip install -e git+https://github.com/petered/artemis.git@avdecord#egg=artemis-ml
```

**Comment by NeighborhoodCoding** [comment]
Edited : 
Thank you very much!!!

**Comment by petered** [comment]
Hold on @NeighborhoodCoding - thank you for the kind words but this is not completed - the issue is still open.  Decord does not work with pyinstaller.  What I just posted was a temporary work-around.

Could you please re-open the issue?

**Comment by wizkdc** [comment]
Hi, I also encountered this problem. After consulting the [documentation for PyInstaller](https://pyinstaller.org/en/v4.8/usage.html#cmdoption-hidden-import), I found out that you can package the decord library by adding the command line option --hidden-import decord. Even though I don't know why PyInstaller can't find the decord library by default, this method works.

**Comment by Mumbaso21** [comment]
I found "more a work-around then a solution" to this problem.
Environment: 

- ubuntu 18.04 
- conda 4.10.1
- python 3.8.11

I also had problems with shared libraries during the application build phase.
I tried different ways found on the internet and github but in the end taking inspiration from @petered answer to try to copy the file after the build directly into the app folder I found the flag `--add-binary` of pyinstaller that allows you to do what @petered suggested but at build time.

This difference is important because if it is copied after the build, an error can occur that still prevents the use of the library despite the file being found:

```
Failed to load dynlib/dll
Most likely this dynlib/dll was not found when the application was frozen
```

In my case the missing library is:
```
RuntimeError: Cannot find the files.
List of candidates:
<path>/libdecord.so
[...]
```

Consequently the pyinstaller command becomes:

`pyinstaller --add-binary=/home/<user>/anaconda3/envs/<env>/lib/python3.8/site-packages/decord/libdecord.so:. <other_flags> file.py`

Please note the `:` and the `.` after the library name, they have [meaning](https://pyinstaller.org/en/v4.8/usage.html#what-to-bundle-where-to-search).
From the documentation:

> **The path separator is platform specific, os.pathsep (which is ; on Windows and : on most unix systems) is used**.
Additional binary files to be added to the executable. See the --add-data option for more details.
This option can be used multiple times.

On Windows is different:

`pyinstaller --add-binary="C:\Users\<user>\Anaconda3\envs\<env>\lib\site-packages\decord\decord.dll;.\decord" <other_flags> file.py`

Please note the `;` and the `.\decord` after the library name.
