### ISSUE TITLE
Can't read video encoded with AV1 codec

### ISSUE THREAD

**Issue by rakhimovv** [dmlc/decord#319]
Hello! Thank you for your work.

I met a problem with reading of certain encoding.
The video ffmpeg encoding information:
```
"vcodec": "libsvtav1",
"pix_fmt": "yuv420p",
"g": 2,
"crf": 30
```

The error:
```
[file @ 0x55fe07de3bc0] Setting default whitelist 'file,crypto'
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55fe07ff1180] Format mov,mp4,m4a,3gp,3g2,mj2 probed with size=2048 and score=100
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55fe07ff1180] ISO: File Type Major Brand: isom
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55fe07ff1180] Unknown dref type 0x206c7275 size 12
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55fe07ff1180] Processing st: 0, edit list 0 - media time: 0, duration: 123909
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55fe07ff1180] Before avformat_find_stream_info() pos: 590687 bytes read:34268 seeks:1 nb_streams:1
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55fe07ff1180] All info found
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55fe07ff1180] After avformat_find_stream_info() pos: 16646 bytes read:67036 seeks:2 frames:1
[AVIOContext @ 0x55fe07d6c9c0] Statistics: 67036 bytes read, 2 seeks
Traceback (most recent call last):
  File "/home/jovyan/rakhimov/gigarobot/dec.py", line 10, in <module>
    vr = VideoReader(path, ctx=cpu(0))
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/micromamba/envs/side_pkg_rr/lib/python3.11/site-packages/decord/video_reader.py", line 54, in __init__
    self._handle = _CAPI_VideoReaderGetVideoReader(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/micromamba/envs/side_pkg_rr/lib/python3.11/site-packages/decord/_ffi/_ctypes/function.py", line 173, in __call__
    check_call(_LIB.DECORDFuncCall(
  File "/home/jovyan/micromamba/envs/side_pkg_rr/lib/python3.11/site-packages/decord/_ffi/base.py", line 78, in check_call
    raise DECORDError(err_str)
decord._ffi.base.DECORDError: [11:30:13] /github/workspace/src/video/video_reader.cc:151: Check failed: st_nb >= 0 (-1128613112 vs. 0) ERROR cannot find video stream with wanted index: -1
```
Video is fine, I checked it visually and also via ffpmeg. Pyav is able to read it too. I guess the problem with the codec support.

The decord version is 0.6.0

installed with
`pip install decord`

**Comment by gcanat** [comment]
Meanwhile this library seems pretty much abandoned, you can try [this one](https://github.com/gcanat/video_reader-rs) instead.

**Comment by rohun-tripathi** [comment]
@gcanat I tried the library for a video that was failing on decord for me. The error was the same as the one OP posted.
For me, decord fails for videos with codec av1 and works for videos with codec H264

On using your library and instead of decord, i got a similar result. I used the following -
`vr = PyVideoReader(path)` 

The ones with H264 load. The ones with av1 fail with - 
`RuntimeError: Error: Decoder not found   `

**Comment by gcanat** [comment]
I suggest open an issue [here](https://github.com/gcanat/video_reader-rs/issues) with detailed information
