### ISSUE TITLE
compile issue

### ISSUE THREAD

**Issue by tea1528** [dmlc/decord#42]
I've successfully compiled and built according to the instruction and even install python binding.

However, I get following error when I try to impor the library:

```
>>> import decord
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/seunghwc/decord/python/decord/__init__.py", line 4, in <module>
    from ._ffi.runtime_ctypes import TypeCode
  File "/home/seunghwc/decord/python/decord/_ffi/runtime_ctypes.py", line 8, in <module>
    from .base import _LIB, check_call
  File "/home/seunghwc/decord/python/decord/_ffi/base.py", line 43, in <module>
    _LIB, _LIB_NAME = _load_lib()
  File "/home/seunghwc/decord/python/decord/_ffi/base.py", line 35, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_GLOBAL)
  File "/home/seunghwc/anaconda3/lib/python3.7/ctypes/__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/seunghwc/decord/build/libdecord.so: undefined symbol: _ZN6decord4cuda12ProcessFrameEyyPhP11CUstream_stttii
```

Below is the result of running `ldd /home/seunghwc/decord/build/libdecord.so`

```
	linux-vdso.so.1 =>  (0x00007ffd1e13c000)
	libavformat.so.58 => /home/seunghwc/ffmpeg_build/lib/libavformat.so.58 (0x00007fc036d23000)
	libavfilter.so.7 => /home/seunghwc/ffmpeg_build/lib/libavfilter.so.7 (0x00007fc0367f4000)
	libavcodec.so.58 => /home/seunghwc/ffmpeg_build/lib/libavcodec.so.58 (0x00007fc035189000)
	libavutil.so.56 => /home/seunghwc/ffmpeg_build/lib/libavutil.so.56 (0x00007fc034d67000)
	libnvrtc.so.10.0 => /opt/cuda/10.0/lib64/libnvrtc.so.10.0 (0x00007fc03374a000)
	libcudart.so.10.0 => /opt/cuda/10.0/lib64/libcudart.so.10.0 (0x00007fc0334d0000)
	libcuda.so.1 => /lib64/libcuda.so.1 (0x00007fc0323c1000)
	libnvidia-ml.so.1 => /lib64/libnvidia-ml.so.1 (0x00007fc031db1000)
	libnvcuvid.so.1 => /lib64/libnvcuvid.so.1 (0x00007fc031901000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007fc0315f9000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fc0312f6000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fc0310e0000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fc030d1d000)
	/lib64/ld-linux-x86-64.so.2 (0x0000558a0cc90000)
	libz.so.1 => /lib64/libz.so.1 (0x00007fc030b06000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fc0308ea000)
	libswscale.so.5 => /home/seunghwc/ffmpeg_build/lib/libswscale.so.5 (0x00007fc030660000)
	libpostproc.so.55 => /home/seunghwc/ffmpeg_build/lib/libpostproc.so.55 (0x00007fc03043f000)
	libswresample.so.3 => /home/seunghwc/ffmpeg_build/lib/libswresample.so.3 (0x00007fc030222000)
	libavresample.so.4 => /home/seunghwc/ffmpeg_build/lib/libavresample.so.4 (0x00007fc030004000)
	librt.so.1 => /lib64/librt.so.1 (0x00007fc02fdfb000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007fc02fbf7000)
	libnvidia-fatbinaryloader.so.410.78 => /lib64/libnvidia-fatbinaryloader.so.410.78 (0x00007fc02f9a9000)
```

I am not sure what went missing during compilation. Can you guide me to it? 

P.S. I've installed using pip but would like to use GPU accelerator.

**Comment by zhreshold** [comment]
Can you try pull the latest master and recompile?

**Comment by tea1528** [comment]
Tried again with the latest pull but the same error.

**Comment by zhreshold** [comment]
The log suggest that some file is not linked, make clean and cmake again?
Attached is the ldd result on my dev workstation:

```
linux-vdso.so.1 (0x00007ffd5d59e000)
	libavformat.so.58 => /usr/lib/x86_64-linux-gnu/libavformat.so.58 (0x00007fe135403000)
	libavfilter.so.7 => /usr/lib/x86_64-linux-gnu/libavfilter.so.7 (0x00007fe134ea3000)
	libavcodec.so.58 => /usr/lib/x86_64-linux-gnu/libavcodec.so.58 (0x00007fe1336fc000)
	libavutil.so.56 => /usr/lib/x86_64-linux-gnu/libavutil.so.56 (0x00007fe1333e0000)
	libcudart.so.10.1 => /usr/local/cuda-10.1/lib64/libcudart.so.10.1 (0x00007fe133164000)
	libcuda.so.1 => /usr/lib/x86_64-linux-gnu/libcuda.so.1 (0x00007fe13235b000)
	libnvidia-ml.so.1 => /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1 (0x00007fe131d35000)
	libnvcuvid.so.1 => /usr/lib/x86_64-linux-gnu/libnvcuvid.so.1 (0x00007fe131821000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fe131602000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fe1313fe000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fe131075000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fe130e5d000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fe130a6c000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fe135c9e000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fe1306ce000)
	libxml2.so.2 => /usr/lib/x86_64-linux-gnu/libxml2.so.2 (0x00007fe13030d000)
	libbz2.so.1.0 => /lib/x86_64-linux-gnu/libbz2.so.1.0 (0x00007fe1300fd000)
	libgme.so.0 => /usr/lib/x86_64-linux-gnu/libgme.so.0 (0x00007fe12feb1000)
	libopenmpt.so.0 => /usr/lib/x86_64-linux-gnu/libopenmpt.so.0 (0x00007fe12fae9000)
	libchromaprint.so.1 => /usr/lib/x86_64-linux-gnu/libchromaprint.so.1 (0x00007fe12f8d6000)
	libbluray.so.2 => /usr/lib/x86_64-linux-gnu/libbluray.so.2 (0x00007fe12f686000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fe12f469000)
	libgnutls.so.30 => /usr/lib/x86_64-linux-gnu/libgnutls.so.30 (0x00007fe12f103000)
	libssh-gcrypt.so.4 => /usr/lib/x86_64-linux-gnu/libssh-gcrypt.so.4 (0x00007fe12ee8f000)
	libswscale.so.5 => /usr/lib/x86_64-linux-gnu/libswscale.so.5 (0x00007fe12ebfc000)
	libpostproc.so.55 => /usr/lib/x86_64-linux-gnu/libpostproc.so.55 (0x00007fe12e9df000)
	libswresample.so.3 => /usr/lib/x86_64-linux-gnu/libswresample.so.3 (0x00007fe12e7c0000)
	libbs2b.so.0 => /usr/lib/x86_64-linux-gnu/libbs2b.so.0 (0x00007fe12e5ba000)
	liblilv-0.so.0 => /usr/lib/liblilv-0.so.0 (0x00007fe12e3a2000)
	librubberband.so.2 => /usr/lib/x86_64-linux-gnu/librubberband.so.2 (0x00007fe12e16a000)
	libmysofa.so.0 => /usr/lib/x86_64-linux-gnu/libmysofa.so.0 (0x00007fe12df5b000)
	libflite_cmu_us_awb.so.1 => /usr/lib/x86_64-linux-gnu/libflite_cmu_us_awb.so.1 (0x00007fe12d966000)
	libflite_cmu_us_kal.so.1 => /usr/lib/x86_64-linux-gnu/libflite_cmu_us_kal.so.1 (0x00007fe12d603000)
	libflite_cmu_us_kal16.so.1 => /usr/lib/x86_64-linux-gnu/libflite_cmu_us_kal16.so.1 (0x00007fe12d02c000)
	libflite_cmu_us_rms.so.1 => /usr/lib/x86_64-linux-gnu/libflite_cmu_us_rms.so.1 (0x00007fe12c994000)
	libflite_cmu_us_slt.so.1 => /usr/lib/x86_64-linux-gnu/libflite_cmu_us_slt.so.1 (0x00007fe12c39e000)
	libflite.so.1 => /usr/lib/x86_64-linux-gnu/libflite.so.1 (0x00007fe12c167000)
	libfribidi.so.0 => /usr/lib/x86_64-linux-gnu/libfribidi.so.0 (0x00007fe12bf50000)
	libass.so.9 => /usr/lib/x86_64-linux-gnu/libass.so.9 (0x00007fe12bd1d000)
	libva.so.2 => /usr/lib/x86_64-linux-gnu/libva.so.2 (0x00007fe12bafc000)
	libvidstab.so.1.1 => /usr/lib/x86_64-linux-gnu/libvidstab.so.1.1 (0x00007fe12b8e9000)
	libzmq.so.5 => /usr/lib/x86_64-linux-gnu/libzmq.so.5 (0x00007fe12b64f000)
	libfontconfig.so.1 => /usr/lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007fe12b40a000)
	libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007fe12b156000)
	libvpx.so.5 => /usr/lib/x86_64-linux-gnu/libvpx.so.5 (0x00007fe12ad0a000)
	libwebpmux.so.3 => /usr/lib/x86_64-linux-gnu/libwebpmux.so.3 (0x00007fe12ab00000)
	libwebp.so.6 => /usr/lib/x86_64-linux-gnu/libwebp.so.6 (0x00007fe12a897000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007fe12a671000)
	librsvg-2.so.2 => /usr/lib/x86_64-linux-gnu/librsvg-2.so.2 (0x00007fe12a439000)
	libgobject-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0 (0x00007fe12a1e5000)
	libglib-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007fe129ece000)
	libcairo.so.2 => /usr/lib/x86_64-linux-gnu/libcairo.so.2 (0x00007fe129bb1000)
	libzvbi.so.0 => /usr/lib/x86_64-linux-gnu/libzvbi.so.0 (0x00007fe129926000)
	libsnappy.so.1 => /usr/lib/x86_64-linux-gnu/libsnappy.so.1 (0x00007fe12971e000)
	libaom.so.0 => /usr/lib/x86_64-linux-gnu/libaom.so.0 (0x00007fe129079000)
	libcodec2.so.0.7 => /usr/lib/x86_64-linux-gnu/libcodec2.so.0.7 (0x00007fe128e26000)
	libgsm.so.1 => /usr/lib/x86_64-linux-gnu/libgsm.so.1 (0x00007fe128c19000)
	libmp3lame.so.0 => /usr/lib/x86_64-linux-gnu/libmp3lame.so.0 (0x00007fe1289a2000)
	libopenjp2.so.7 => /usr/lib/x86_64-linux-gnu/libopenjp2.so.7 (0x00007fe12874c000)
	libopus.so.0 => /usr/lib/x86_64-linux-gnu/libopus.so.0 (0x00007fe128502000)
	libshine.so.3 => /usr/lib/x86_64-linux-gnu/libshine.so.3 (0x00007fe1282f7000)
	libspeex.so.1 => /usr/lib/x86_64-linux-gnu/libspeex.so.1 (0x00007fe1280dd000)
	libtheoraenc.so.1 => /usr/lib/x86_64-linux-gnu/libtheoraenc.so.1 (0x00007fe127e9e000)
	libtheoradec.so.1 => /usr/lib/x86_64-linux-gnu/libtheoradec.so.1 (0x00007fe127c80000)
	libtwolame.so.0 => /usr/lib/x86_64-linux-gnu/libtwolame.so.0 (0x00007fe127a5d000)
	libvorbis.so.0 => /usr/lib/x86_64-linux-gnu/libvorbis.so.0 (0x00007fe127832000)
	libvorbisenc.so.2 => /usr/lib/x86_64-linux-gnu/libvorbisenc.so.2 (0x00007fe127589000)
	libwavpack.so.1 => /usr/lib/x86_64-linux-gnu/libwavpack.so.1 (0x00007fe12735f000)
	libx264.so.155 => /usr/lib/x86_64-linux-gnu/libx264.so.155 (0x00007fe126ea2000)
	libx265.so.179 => /usr/lib/x86_64-linux-gnu/libx265.so.179 (0x00007fe125d35000)
	libxvidcore.so.4 => /usr/lib/x86_64-linux-gnu/libxvidcore.so.4 (0x00007fe125a24000)
	libva-drm.so.2 => /usr/lib/x86_64-linux-gnu/libva-drm.so.2 (0x00007fe125821000)
	libva-x11.so.2 => /usr/lib/x86_64-linux-gnu/libva-x11.so.2 (0x00007fe12561b000)
	libvdpau.so.1 => /usr/lib/x86_64-linux-gnu/libvdpau.so.1 (0x00007fe125417000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007fe1250df000)
	libdrm.so.2 => /usr/lib/x86_64-linux-gnu/libdrm.so.2 (0x00007fe124ece000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fe124cc6000)
	libicuuc.so.60 => /usr/lib/x86_64-linux-gnu/libicuuc.so.60 (0x00007fe12490e000)
	libmpg123.so.0 => /usr/lib/x86_64-linux-gnu/libmpg123.so.0 (0x00007fe1246af000)
	libvorbisfile.so.3 => /usr/lib/x86_64-linux-gnu/libvorbisfile.so.3 (0x00007fe1244a7000)
	libavcodec.so.57 => /usr/lib/x86_64-linux-gnu/libavcodec.so.57 (0x00007fe122d86000)
	libavutil.so.55 => /usr/lib/x86_64-linux-gnu/libavutil.so.55 (0x00007fe122afa000)
	libp11-kit.so.0 => /usr/lib/x86_64-linux-gnu/libp11-kit.so.0 (0x00007fe1227cb000)
	libidn2.so.0 => /usr/lib/x86_64-linux-gnu/libidn2.so.0 (0x00007fe1225ae000)
	libunistring.so.2 => /usr/lib/x86_64-linux-gnu/libunistring.so.2 (0x00007fe122230000)
	libtasn1.so.6 => /usr/lib/x86_64-linux-gnu/libtasn1.so.6 (0x00007fe12201d000)
	libnettle.so.6 => /usr/lib/x86_64-linux-gnu/libnettle.so.6 (0x00007fe121de7000)
	libhogweed.so.4 => /usr/lib/x86_64-linux-gnu/libhogweed.so.4 (0x00007fe121bb3000)
	libgmp.so.10 => /usr/lib/x86_64-linux-gnu/libgmp.so.10 (0x00007fe121932000)
	libgcrypt.so.20 => /lib/x86_64-linux-gnu/libgcrypt.so.20 (0x00007fe121616000)
	libgssapi_krb5.so.2 => /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2 (0x00007fe1213cb000)
	libsoxr.so.0 => /usr/lib/x86_64-linux-gnu/libsoxr.so.0 (0x00007fe121168000)
	libserd-0.so.0 => /usr/lib/x86_64-linux-gnu/libserd-0.so.0 (0x00007fe120f52000)
	libsord-0.so.0 => /usr/lib/x86_64-linux-gnu/libsord-0.so.0 (0x00007fe120d47000)
	libsratom-0.so.0 => /usr/lib/x86_64-linux-gnu/libsratom-0.so.0 (0x00007fe120b3d000)
	libsamplerate.so.0 => /usr/lib/x86_64-linux-gnu/libsamplerate.so.0 (0x00007fe1207d1000)
	libfftw3.so.3 => /usr/lib/x86_64-linux-gnu/libfftw3.so.3 (0x00007fe1203cf000)
	libflite_usenglish.so.1 => /usr/lib/x86_64-linux-gnu/libflite_usenglish.so.1 (0x00007fe1201a6000)
	libflite_cmulex.so.1 => /usr/lib/x86_64-linux-gnu/libflite_cmulex.so.1 (0x00007fe11ff11000)
	libasound.so.2 => /usr/lib/x86_64-linux-gnu/libasound.so.2 (0x00007fe11fc0a000)
	libharfbuzz.so.0 => /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0 (0x00007fe11f96c000)
	libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007fe11f73d000)
	libsodium.so.23 => /usr/lib/x86_64-linux-gnu/libsodium.so.23 (0x00007fe11f4ec000)
	libpgm-5.2.so.0 => /usr/lib/x86_64-linux-gnu/libpgm-5.2.so.0 (0x00007fe11f2a0000)
	libnorm.so.1 => /usr/lib/x86_64-linux-gnu/libnorm.so.1 (0x00007fe11ef70000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007fe11ed3e000)
	libpng16.so.16 => /usr/lib/x86_64-linux-gnu/libpng16.so.16 (0x00007fe11eb0c000)
	libgdk_pixbuf-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0 (0x00007fe11e8e8000)
	libgio-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0 (0x00007fe11e549000)
	libpangocairo-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libpangocairo-1.0.so.0 (0x00007fe11e33c000)
	libpangoft2-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0 (0x00007fe11e126000)
	libpango-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0 (0x00007fe11ded9000)
	libcroco-0.6.so.3 => /usr/lib/x86_64-linux-gnu/libcroco-0.6.so.3 (0x00007fe11dc9e000)
	libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007fe11da96000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007fe11d824000)
	libpixman-1.so.0 => /usr/lib/x86_64-linux-gnu/libpixman-1.so.0 (0x00007fe11d57f000)
	libxcb-shm.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-shm.so.0 (0x00007fe11d37c000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007fe11d154000)
	libxcb-render.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-render.so.0 (0x00007fe11cf47000)
	libXrender.so.1 => /usr/lib/x86_64-linux-gnu/libXrender.so.1 (0x00007fe11cd3d000)
	libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007fe11cb2b000)
	libogg.so.0 => /usr/lib/x86_64-linux-gnu/libogg.so.0 (0x00007fe11c922000)
	libnuma.so.1 => /usr/lib/x86_64-linux-gnu/libnuma.so.1 (0x00007fe11c717000)
	libXfixes.so.3 => /usr/lib/x86_64-linux-gnu/libXfixes.so.3 (0x00007fe11c511000)
	libicudata.so.60 => /usr/lib/x86_64-linux-gnu/libicudata.so.60 (0x00007fe11a968000)
	libswresample.so.2 => /usr/lib/x86_64-linux-gnu/libswresample.so.2 (0x00007fe11a749000)
	libcrystalhd.so.3 => /usr/lib/x86_64-linux-gnu/libcrystalhd.so.3 (0x00007fe11a52e000)
	libx265.so.146 => /usr/lib/x86_64-linux-gnu/libx265.so.146 (0x00007fe1198ad000)
	libx264.so.152 => /usr/lib/x86_64-linux-gnu/libx264.so.152 (0x00007fe119508000)
	libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007fe1192f3000)
	libkrb5.so.3 => /usr/lib/x86_64-linux-gnu/libkrb5.so.3 (0x00007fe11901d000)
	libk5crypto.so.3 => /usr/lib/x86_64-linux-gnu/libk5crypto.so.3 (0x00007fe118deb000)
	libcom_err.so.2 => /lib/x86_64-linux-gnu/libcom_err.so.2 (0x00007fe118be7000)
	libkrb5support.so.0 => /usr/lib/x86_64-linux-gnu/libkrb5support.so.0 (0x00007fe1189dc000)
	libgraphite2.so.3 => /usr/lib/x86_64-linux-gnu/libgraphite2.so.3 (0x00007fe1187af000)
	libgmodule-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgmodule-2.0.so.0 (0x00007fe1185ab000)
	libselinux.so.1 => /lib/x86_64-linux-gnu/libselinux.so.1 (0x00007fe118383000)
	libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007fe118168000)
	libmount.so.1 => /lib/x86_64-linux-gnu/libmount.so.1 (0x00007fe117f14000)
	libthai.so.0 => /usr/lib/x86_64-linux-gnu/libthai.so.0 (0x00007fe117d0b000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007fe117b07000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007fe117901000)
	libkeyutils.so.1 => /lib/x86_64-linux-gnu/libkeyutils.so.1 (0x00007fe1176fd000)
	libblkid.so.1 => /lib/x86_64-linux-gnu/libblkid.so.1 (0x00007fe1174b0000)
	libdatrie.so.1 => /usr/lib/x86_64-linux-gnu/libdatrie.so.1 (0x00007fe1172a9000)
	libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007fe117094000)
	libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00007fe116e8d000)
```

**Comment by densechen** [comment]
I faced the some Error:

```bash
>>> import decord
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hadoop-mtcv/decord/python/decord/__init__.py", line 4, in <module>
    from ._ffi.runtime_ctypes import TypeCode
  File "/home/hadoop-mtcv/decord/python/decord/_ffi/runtime_ctypes.py", line 8, in <module>
    from .base import _LIB, check_call
  File "/home/hadoop-mtcv/decord/python/decord/_ffi/base.py", line 47, in <module>
    _LIB, _LIB_NAME = _load_lib()
  File "/home/hadoop-mtcv/decord/python/decord/_ffi/base.py", line 39, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_GLOBAL)
  File "/usr/local/conda/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/hadoop-mtcv/decord/build/libdecord.so: undefined symbol: cuvidDestroyDecoder
>>> 
```

Can you help me?

**Comment by spriya20** [comment]
@densechen Were you able to fix this?

**Comment by uvikas** [comment]
@spriya20 Were you able to fix this?
