### ISSUE TITLE
[feature requests] read video from url

### ISSUE THREAD

**Issue by AceCoooool** [dmlc/decord#47]
opencv support read video in rtps or some other form to read video online.
Does decord support it ?

**Comment by zhreshold** [comment]
It's already supported. You can pass `url` instead of `file path` to `VideoReader`.
The protocols are dependent on the FFmpeg on your machine. HTTP protocol works on mine.

**Comment by DelightRun** [comment]
@zhreshold Does decord support reading from file-like object?

**Comment by zhreshold** [comment]
@DelightRun See #75 which adds support for reading from file-like object

**Comment by Scheaven** [comment]
> It's already supported. You can pass `url` instead of `file path` to `VideoReader`. The protocols are dependent on the FFmpeg on your machine. HTTP protocol works on mine.

It's already supported. You can pass url instead of file path to VideoReader. The protocols are dependent on the FFmpeg on your machine. HTTP protocol works on mine.
Do you support HTTPS? I read the video stream error as follows(OpenCV can read changed URL video streams ):

[18:13:47] /github/workspace/src/video/video_reader.cc:83: ERROR opening: https://api-monitor.live.360.cn/DeviceQvod/getQvod?product_key=967e6e8a9f55&device_sn=360M476fd9a60716d9&start_ts=1633903001&end_ts=1633903201&expire=1634633824&sign=bd483f576dfc8e4d7b986a9b16dae1a3, Protocol not found                                                                                      Traceback (most recent call last):                                                                                                                                                             File "03_comparison.py", line 60, in videoToArrayByDecord                                                                                                                                      vr = decord.VideoReader(video_path, ctx=decord.cpu(0), width=width, height=height, num_threads=10)                                                                                         File "/home/scheaven/anaconda3/envs/py3/lib/python3.8/site-packages/decord/video_reader.py", line 57, in __init__                                                                              raise RuntimeError("Error reading " + uri + "...")                                                                                                                                       RuntimeError: Error reading https://api-monitor.live.360.cn/DeviceQvod/getQvod?product_key=967e6e8a9f55&device_sn=360M476fd9a60716d9&start_ts=1633903001&end_ts=1633903201&expire=1634633824&sign=bd483f576dfc8e4d7b986a9b16dae1a3...                                                                                                                                                                                                                                                                                                                                                  During handling of the above exception, another exception occurred:                                                                                                                                                                                                                                                                                                                       Traceback (most recent call last):                                                                                                                                                             File "03_comparison.py", line 92, in <module>                                                                                                                                                  video_tensor_decord = videoToArrayByDecord(video_path, height, width)                                                                                                                      File "03_comparison.py", line 64, in videoToArrayByDecord                                                                                                                                      raise Exception('Can\'t load video {}\n{}'.format(video_path, str(e)))                                                                                                                   Exception: Can't load video https://api-monitor.live.360.cn/DeviceQvod/getQvod?product_key=967e6e8a9f55&device_sn=360M476fd9a60716d9&start_ts=1633903001&end_ts=1633903201&expire=1634633824&sign=bd483f576dfc8e4d7b986a9b16dae1a3                                                                                                                                                        Error reading https://api-monitor.live.360.cn/DeviceQvod/getQvod?product_key=967e6e8a9f55&device_sn=360M476fd9a60716d9&start_ts=1633903001&end_ts=1633903201&expire=1634633824&sign=bd483f576dfc8e4d7b986a9b16dae1a3...

**Comment by LeonLIU08** [comment]
@Scheaven have you solved this problem? I have the same problem here.
